# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.abstract_youtube_fetcher:
        abstract: true
        shared: false
        arguments: ['@mailer']

    app.youtube_fetcher_without_logger:
        class: AppBundle\Youtube\YoutubeFetcher
        parent: app.abstract_youtube_fetcher

    app.youtube_fetcher_with_logger:
        class: AppBundle\Youtube\YoutubeFetcher
        calls:
            - [setLogger, ['@logger']]
        parent: app.abstract_youtube_fetcher

    app.youtube_fetcher:
        alias: app.youtube_fetcher_with_logger

    app.youtube.twig_extension:
        class: AppBundle\Youtube\TwigExtension
        arguments: ['@app.youtube_fetcher']
        tags:
            - { name: twig.extension }

    app.joboffer.headerlistener:
        class: AppBundle\JobOffer\JobOfferHeaderListener
        tags:
            - {name: kernel.event_listener, event: kernel.response, priority: -1024}

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
